### ISSUE TITLE
bug(search): Wrong bcp47 code when searching for "German" with embedded search

### ISSUE THREAD

**Issue by ermshiperete** [keymanapp/api.keyman.com#197]
When using the URL https://keyman.com/go/linux/17.0/download-keyboards and searching for "German", the first result ("[EuroLatin (SIL)](https://keyman.com/keyboards/sil_euro_latin?bcp47=pdt)(German language)") has the bcp47 code _pdt_ instead of _de_.

Things work with the regular search page (https://keyman.com/keyboards?q=german).

See https://github.com/keymanapp/keyman/issues/9114.

**Comment by mcdurdin** [comment]
This is difficult to solve. I think we've encountered it before. The problem is that `pdt` and `de` both have the name 'German' in the langtag database:

## langtag

```
tag	full		iso639_3	region	regionname	name			sldr	nophonvars	script	suppress	windows
de	de-Latn-DE	deu		DE	Germany		German, Standard	1	NULL		Latn	1		de-DE
pdt	pdt-Latn-CA	pdt		CA	Canada		Plautdietsch		0	NULL		Latn	NULL		pdt-Latn
```

## langtag_name

```
_id	tag	name	name_kd	nametype
12855	de	German	German	0
12868	de	German	German	3
44069	pdt	German	German	0
```

This means that the weight given to both results is identical (we are only using nametype=0 at present).

Possible ways forward:

1. Also compare against name in the primary langtag table to give additional weight to 'German' (because 'German, Standard') -- this will need careful checking to make sure it doesn't badly weight other search results.
2. Remove pdt from sil_euro_latin (a bit of a backwards step?)
3. See if we can merge multiple matches for a given term to give additional weight (i.e. use search result for nametype=3 (IANA name) as above also to give additional weight to de).

**Comment by ermshiperete** [comment]
Where does German for `pdt` in `langtag_name` come from?

**Comment by darcywong00** [comment]
Maybe from [langtags.json](https://github.com/keymanapp/keyman/blob/master/resources/standards-data/langtags/langtags.json)

```json
    {
        "full": "pdt-Latn-CA",
        "iana": [ "Plautdietsch" ],
        "iso639_3": "pdt",
        "localnames": [ "Plautdietsch" ],
        "name": "Plautdietsch",
        "names": [ "German", "Low German", "Mennonite German", "Mennonite Low German", "Mennoniten Platt" ],
        "region": "CA",
        "regionname": "Canada",
        "regions": [ "AR", "BO", "BR", "BZ", "CR", "DE", "KZ", "MX", "PY", "RU", "US", "UY" ],
        "script": "Latn",
        "sldr": false,
        "tag": "pdt",
        "tags": [ "pdt-CA", "pdt-Latn" ],
        "windows": "pdt-Latn"
    },
```

**Comment by darcywong00** [comment]
Also see #148 (on staging)
