### ISSUE TITLE
Cloud Services API not listing some keyboards

### ISSUE THREAD

**Issue by ramesh-k** [keymanapp/api.keyman.com#84]
It is observed that some keyboards are not included in returned JSON data of API call - https://api.keyman.com/cloud/4.0/keyboards

**Examples :-**
- [Devanagari - INSCRIPT Basic](https://keyman.com/keyboards/basic_kbdindev)
- [Malar Malayalam](https://keyman.com/keyboards/malar_malayalam)
- [Tamil WinScript [NLCI]](https://keyman.com/keyboards/nlci_tamil_winscript)

**Comment by mcdurdin** [comment]
In order to see these keyboards, you need to include a version parameter: `?version=10.0` (use the version of Keyman Engine you are working with). These keyboards are not compatible with versions of Keyman earlier than 10.0; for compatibility reasons, the API defaults to returning keyboards compatible with Keyman Engine for Web 2.0.

For example https://api.keyman.com/cloud/4.0/keyboards/basic_kbdindev?version=10.0 returns the correct record.

You should also include the extra parameter `languageidtype=bcp47` to get BCP 47 codes for languages rather than ISO639-3 codes.

So, the final query would be https://api.keyman.com/cloud/4.0/keyboards?version=10.0&languageidtype=bcp47
